# Generated by Django 2.2.6 on 2019-11-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
