# Generated by Django 2.2.6 on 2019-11-15 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_auto_20191115_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('estado', models.TextField(max_length=800)),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orden',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Orden_n_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Item')),
            ],
            options={
                'db_table': 'Orden_n_Item',
                'managed': True,
            },
        ),
    ]
